apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgate
spec:
  replicas: 1
  selector : 
    matchLabels : 
      run: mgate
  template:
    metadata:
      labels:
        run: mgate
    spec:
      containers:
      - name: mgate
        image: registry.gitlab.com//mgate:latest
        resources:
          requests:
            cpu: "4"
            memory: "10Gi"
        ports : 
        - containerPort : 8080
        volumeMounts:
        - name : config
          mountPath : /usr/local/config
      imagePullSecrets:
      - name: gitlab-deploy-token
      volumes:
        - name: config
          configMap:
            name: mgate-config
      
