apiVersion: v1
kind: Service
metadata:
  name: schema-registry-production
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: schema-registry-production
  type: NodePort

